//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vecherom_Zavtra2_WebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class vz2Entities : DbContext
    {
        public vz2Entities()
            : base("name=vz2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCfg> UserCfgs { get; set; }
    
        public virtual int procAddUser(string pUsername, string pPassword, ObjectParameter responseMessage)
        {
            var pUsernameParameter = pUsername != null ?
                new ObjectParameter("pUsername", pUsername) :
                new ObjectParameter("pUsername", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procAddUser", pUsernameParameter, pPasswordParameter, responseMessage);
        }
    
        public virtual int procLogin(string pUsername, string pPassword, ObjectParameter responseMessage, ObjectParameter userID)
        {
            var pUsernameParameter = pUsername != null ?
                new ObjectParameter("pUsername", pUsername) :
                new ObjectParameter("pUsername", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procLogin", pUsernameParameter, pPasswordParameter, responseMessage, userID);
        }
    }
}
